import { useState } from 'react';
import { Plus, Trash2, Users } from 'lucide-react';
import type { BoardData, TeamMember } from '../types/kanban';
import { STAGE_COLORS } from '../utils/board';
interface Props { data: BoardData; onAdd: (member: TeamMember) => Promise<boolean>; onRemove: (id: string) => Promise<boolean>; busy: boolean; }
export function TeamView({ data, onAdd, onRemove, busy }: Props) {
  const [name, setName] = useState(''); const [email, setEmail] = useState(''); const [role, setRole] = useState('');
  return <div className="team-layout"><section className="panel"><div className="panel-heading"><Users size={17} /><h2>Osoby w projekcie</h2><span className="count">{data.members.length}</span></div><p className="panel-description">Lista osób, którym można przypisywać zadania. Dostęp do logowania nadaje osobno administrator.</p>
    {data.members.map(m => <div className="person-row" key={m.id}><span className="avatar" style={{ background: m.color + '18', color: m.color }}>{m.name.slice(0, 2).toUpperCase()}</span><div><strong>{m.name}</strong><p>{m.role || 'Zespół'}{m.email && ' · ' + m.email}</p></div><span className="count">{data.tasks.filter(t => t.assigneeId === m.id && t.status !== 'done').length} aktywnych</span><button className="icon-button danger" disabled={busy} aria-label={'Usuń osobę: ' + m.name} onClick={() => { if (confirm('Usunąć osobę z listy? Jej zadania pozostaną bez przypisania. To nie cofa dostępu do logowania.')) void onRemove(m.id); }}><Trash2 size={16} /></button></div>)}
    {!data.members.length && <div className="empty-state">Dodaj pierwszą osobę do listy projektu.</div>}
    </section><section className="panel"><h2>Dodaj osobę do listy</h2><form className="form-stack" onSubmit={async e => { e.preventDefault(); if (await onAdd({ id: crypto.randomUUID(), name: name.trim(), email: email.trim(), role: role.trim(), color: STAGE_COLORS[data.members.length % STAGE_COLORS.length], status: 'active' })) { setName(''); setEmail(''); setRole(''); } }}><label>Imię i nazwisko<input value={name} onChange={e => setName(e.target.value)} maxLength={120} required /></label><label>E-mail <span className="muted">(opcjonalnie)</span><input type="email" value={email} onChange={e => setEmail(e.target.value)} maxLength={254} /></label><label>Rola w projekcie<input value={role} onChange={e => setRole(e.target.value)} placeholder="np. Projektant" maxLength={120} /></label><button className="button primary" disabled={busy || data.members.length >= 200}><Plus size={16} />Dodaj osobę</button></form><p className="panel-description">Dodanie osoby nie wysyła zaproszenia i nie tworzy konta.</p></section></div>;
}

